---
  - name: Configure Single Area OSPF
    hosts: routers
    gather_facts: false
    connection: local
    vars:
      cli:
        username: cisco
        password: cisco123!

    tasks:

      - name: Configure OSPF for ACCOUNTING
        when: ansible_host == "192.168.0.1"
        ios_config:
          provider: "{{ cli }}"
          parents: router ospf 1
          lines:
            - network 192.168.0.0 0.0.0.255 area 0
            - passive-interface FastEthernet0/0


      - name: print ip route
        ios_command:
          provider: "{{ cli }}"
          commands:
            - show running-config
        register: config

      - name: SAVE OUTPUT TO ./iosconfig/ 
        copy:
          content: "{{config.stdout[0]}}"
          dest: "iosconfig/showrun{{inventory_hostname}}.txt"

      - name: Save Configuration
        ios_config:
          provider: "{{ cli }}"
          lines:
            - do write